env:
  DENY_LIST: "default,kube-system" # Comma-separated list of namespaces to ignore
  RECONCILE_WAIT: "10s"            # Reconciliation delay
  WATCH_NAMESPACE: ""              # Namespace to watch or empty string to watch all namespaces, To watch multiple namespaces add , into string. Ex: WATCH_NAMESPACE: "ns1,ns2,ns3"

replicaCount: 1

image:
  repository: druidio/druid-operator
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: [ ]
nameOverride: ""
fullnameOverride: ""

livenessProbe: { }
  # httpGet:
  #   path: /healthz
  #   port: 8081
  # initialDelaySeconds: 15
# periodSeconds: 20

readinessProbe: { }
  # httpGet:
  #   path: /readyz
  #   port: 8081
  # initialDelaySeconds: 5
# periodSeconds: 10

rbac:
  create: true

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: { }
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: { }

podSecurityContext: { }
# fsGroup: 2000

securityContext: { }


resources: { }


tolerations:
  - key: "DRUID"
    operator: "Exists"
    effect: "NoExecute"
nodeSelector:
  TYPE: "DRUID"

affinity: { }

crd:
  enabled: true
